// GENERATED by scripts/generate-template-previews.ts — DO NOT HAND-EDIT.
// Regenerate with: npm run templates:previews

import type { TemplateKey } from "./registry";

/**
 * TMPL-06 / 05.1 D-05.
 *
 * PARTIAL BY DESIGN. A missing key IS the signal that the picker falls back
 * to `<TemplateThumbnail>` (05-09's CSS-wireframe component). This is the
 * fact D-05 branches on, and it is precisely what a hand-authored
 * `previewImageKey` field on `TemplateDefinition` structurally could not
 * express — a non-optional field is either always present (a lie, before
 * generation has run) or optional in a way that erases the distinction
 * between "no preview yet" and "preview generation failed for this one key".
 *
 * Why this is not a field on `TEMPLATES`: the registry records design
 * decisions a human chose (`segment`, `minTier`, `sections`); this file
 * records generation state a script produced. `registry.ts` is a
 * 1262-line hand-edited file and a script must not rewrite it — same
 * posture as `src/generated/prisma/**`, which is also never hand-edited.
 *
 * Keys are emitted in `TEMPLATE_KEYS` order so a regeneration diff is
 * stable — an unordered object literal would reorder itself on every run
 * for no reason related to the actual content change.
 *
 * It ships EMPTY until `npm run templates:previews` has been run (plan
 * 05.1-08); an empty manifest means every tile renders the wireframe
 * fallback, which is correct, not broken.
 */
export interface TemplatePreview {
  readonly width: number;
  readonly height: number;
  readonly bytes: number;
  /** ISO 8601. */
  readonly generatedAt: string;
}

export const TEMPLATE_PREVIEWS: Readonly<
  Partial<Record<TemplateKey, TemplatePreview>>
> = {
  "flagship-fashion": { width: 800, height: 500, bytes: 10862, generatedAt: "2026-09-08T04:03:21.820Z" },
  "fashion-classic": { width: 800, height: 500, bytes: 14768, generatedAt: "2026-09-08T04:02:47.188Z" },
  "fashion-edit": { width: 800, height: 500, bytes: 13612, generatedAt: "2026-09-08T04:02:50.584Z" },
  "electronics-grid": { width: 800, height: 500, bytes: 17446, generatedAt: "2026-09-08T04:02:54.548Z" },
};
